name: Generate Snake Animation

on:
  # Executa automaticamente a cada 24 horas
  schedule:
    - cron: "0 */24 * * *"
  
  # Permite executar manualmente o trabalho a qualquer momento
  workflow_dispatch:
  
  # Executa em cada push na branch principal (main)
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: CamiloACarvalho
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
